#!/bin/sh

usage()
{
	echo "Usage: $0 [source] [destination]"
	exit 0
}

fileinfo()
{
	echo "% File info:"
	awk '/^p / {print $3 " " $3 " " $4; exit}' "$1"
}

contents()
{
	echo "% Contents:"
	sed -n -e 's/^c/%/p' -e 's/^a //p' "$1"
}

main()
{
	if [[ $# -lt 2 ]]; then
		usage
	fi

	(echo "% Generated by $0 by Bert Peters" \
		&& fileinfo $1 \
		&& contents $1) > $2
}

main "$@"
